### ISSUE TITLE
Cannot make an endpoint with the same name of a recently deleted endpoint

### ISSUE THREAD

**Issue by davidsiaw** [degica/barcelona#550] opened 2020-02-26 08:23 UTC
# Context

If you create an endpoint, delete it and recreate one with the same name shortly after, you get an `internal_server_error`

# How to test
1. `bcn endpoint create --district default poky`
2. `bcn endpoint delete --district default poky`
3. `bcn endpoint create --district default poky`
4. Observe that it returns `internal_server_error`

**Comment by Yuuki77** [comment] 2021-03-23 07:20
Hmm could not reproduce the issue
close it

**Closed by Yuuki77** 2021-03-23 07:20 UTC
